#!/bin/bash
#This shell will build, package and deploy the various demo installations on titanium

#build and package application
LANG=en_US ant buildpackage
wait

#stop tomcat
sudo /etc/init.d/tomcat5.5 stop
wait

#install haitiOpenElis
if [ -f ./warRoot/openElis.war ] 
then
   echo "installing haitiOpenElis"

   if [ -d /usr/share/tomcat5.5/webapps/haitiOpenElis ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/haitiOpenElis
   fi		
   
   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/haitiOpenElis.war

 echo "installing haitiOpenElis_English"

   if [ -d /usr/share/tomcat5.5/webapps/haitiOpenElis_English ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/haitiOpenElis_English
   fi		
   
   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/haitiOpenElis_English.war


   echo "installing CDIOpenElis"

   if [ -d /usr/share/tomcat5.5/webapps/CDIOpenElis ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/CDIOpenElis
   fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/CDIOpenElis.war

   echo "installing CDIOpenElis_English"

   if [ -d /usr/share/tomcat5.5/webapps/CDIOpenElis_English ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/CDIOpenElis_English
   fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/CDIOpenElis_English.war


   echo "installing LNSP_HaitiOpenElis"

if [ -d /usr/share/tomcat5.5/webapps/LNSP_HaitiOpenElis ]
then
   sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/LNSP_HaitiOpenElis
fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/LNSP_HaitiOpenElis.war

   echo "installing CI_LNSPOpenElis"

if [ -d /usr/share/tomcat5.5/webapps/CI_LNSPOpenElis ]
then
   sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/CI_LNSPOpenElis
fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/CI_LNSPOpenElis.war

   echo "installing CDI_RegLabOpenElis"

   if [ -d /usr/share/tomcat5.5/webapps/CDI_RegLabOpenElis ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/CDI_RegLabOpenElis
   fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/CDI_RegLabOpenElis.war

#for new instance copy-modify from here to end marker 
   echo "installing CI_IPCIOpenElis"

   if [ -d /usr/share/tomcat5.5/webapps/CI_IPCIOpenElis ]
   then
       sudo -u tomcat55 rm -r /usr/share/tomcat5.5/webapps/CI_IPCIOpenElis
   fi		

   sudo -u tomcat55 cp warRoot/openElis.war /usr/share/tomcat5.5/webapps/CI_IPCIOpenElis.war
#end marker
else
   echo "missing openElis.war file" 
fi

#update database
LANG=en_US.UTF-8 ant updateDB
wait

#restart tomcat
sudo /etc/init.d/tomcat5.5 start
